### PR TITLE
Add IPv6 support

### PR DESCRIPTION
**Pull request by ingvaldlorentzen**
Hi, 

Love this package, but one thing missing is IPv6 support. 
I'm no networking expert, so I would love some help with this. 

I've added logic for resolving IPv6 addresses, but the line:
`with socket.socket(socket.AF_INET, socket.SOCK_RAW, socket.IPPROTO_ICMP) as sock:`
in the `ping` function is an issue.   
As the socket has to be created with `socket.AF_INET6`.  
So more structural changes are needed. 

Also, when testing, replacing the `socket.AF_INET` with `socket.AF_INET6` does not work. 
The line `sock.setsockopt(socket.SOL_IP, socket.IP_TTL, ttl)` seems to be the problem.  
I tried figuring out how to solve this, but have come up empty handed. 

Any help and/or feedback would be appreciated!

### CODE REVIEW

**Comment by kyan001** [comment]
Hi Ingvald,

Thanks for the suggestion and the pull request.
I will look into this problem. I don't have IPv6 support here in my network provider, so I cant say when the IPv6 feature is going to be supported.

The root reason of your code does not work, is that IPv6 Packet has a different structure compare to IPv4. Here are some links you can check: [IPv6](https://en.wikipedia.org/wiki/IPv6), [ICMPv6](https://en.wikipedia.org/wiki/Internet_Control_Message_Protocol_for_IPv6)

**Comment by ingvaldlorentzen** [comment]
Hi,

Thanks for taking a look at this.

I can provide a VM with either dual IPv4 and IPv6 support, or just IPv6 support so that you could test this, if that's something your interested in.

**Comment by ingvaldlorentzen** [comment]
I added some more IPv6 code. Still not working though. 

It's a bit messy, a different structure is probably preferable, but I wanted to touch as little of the existing code until it's working.

**Comment by kyan001** [comment]
Hi, I had a quick look for your code, here is something might help:

1. at ping3.py:223, The protocol number should be `socket.IPPROTO_ICMPV6`, which is `58`, the old `socket.IPPROTO_ICMP` is `1`
```python
with socket.socket(socket.AF_INET if ip_type == '4' else socket.AF_INET6,
                       socket.SOCK_RAW,
                       socket.IPPROTO_ICMP) as sock:  # <-- this line
```

2. Since there only IPv4 and IPv6, how about we name the arg `send_one_ping(..., ipv6=False)` and set to True when called for IPv6.

3. IcmpType number should be a new class of enum, Better not using the same class as IPv4, since same number may represent different type.

**Comment by Huthesh** [comment]
is IPv6 supported now?

**Comment by kyan001** [comment]
> is IPv6 supported now?

nope.

**Comment by JonasKs** [comment]
Ref this PR, we’ve started using icmplib, which has asyncio and ipv6 support. https://github.com/ValentinBELYN/icmplib

**Pull request closed without merging**
